/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.0
 *
 * Project: 'M55_HP.Release+DevKit-E8' 
 * Target:  'Release+DevKit-E8' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.26.5 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55
/* PyTorch::Machine Learning:ExecuTorch:Backend EthosU@1.1.0-rc1-build.12 */
#define EXECUTORCH_BUILD_ARM_BAREMETAL 1
        #define ET_USE_ETHOS_U_BACKEND 1
/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.1.0-rc1-build.12 */
/* ExecuTorch global configuration */
        #define C10_USING_CUSTOM_GENERATED_MACROS
        #define FLATBUFFERS_MAX_ALIGNMENT 1024
        #define FLATBUFFERS_LOCALE_INDEPENDENT 0


#endif /* PRE_INCLUDE_GLOBAL_H */
