#!/usr/bin/env bash
# Build, flash and log one configuration of the CSP4CMSIS regression suite on
# the DK-E8 (RTSS-HP). See README.md in this directory.
#
# usage: ./hwtest.sh build|flash|capture|collect|run <lib> <build type> <toolchain>
#   lib         v1 (the v1.0.0 worktree) or v2 (the CSP4CMSIS working tree)
#   build type  RTX5 | FreeRTOS | RTX5-NoHeap | FreeRTOS-NoHeap
#   toolchain   AC6 | GCC
#
# Environment (defaults in brackets):
#   HWTEST_LIB_V1    v1.0.0 tree            [$HOME/src/CSP4CMSIS-v1.0.0]
#   HWTEST_LIB_V2    2.0 working tree       [$HOME/src/CSP4CMSIS]
#   HWTEST_SETOOLS   SETOOLS directory      [<repo>/tools/setools/app-release-exec-linux]
#   HWTEST_UART      console port           [/dev/ttyACM0]
#   HWTEST_TIMEOUT   capture timeout, s     [1800]
#   HWTEST_EXTRA     extra cbuild options   []
#   HWTEST_CONSOLE_LOG  minicom -C log for collect [$HOME/hwtest_console.log]
#   AC6_TOOLCHAIN_6_24_0 / GCC_TOOLCHAIN_14_2_1, CMSIS_PACK_ROOT, cbuild on PATH.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
LIB_V1="${HWTEST_LIB_V1:-$HOME/src/CSP4CMSIS-v1.0.0}"
LIB_V2="${HWTEST_LIB_V2:-$HOME/src/CSP4CMSIS}"
SETOOLS="${HWTEST_SETOOLS:-$REPO/tools/setools/app-release-exec-linux}"
UART="${HWTEST_UART:-/dev/ttyACM0}"
TIMEOUT="${HWTEST_TIMEOUT:-1800}"
IMAGE_NAME="csp4cmsis_hwtest_hp.bin"

die() { echo "hwtest: $*" >&2; exit 1; }

[[ $# -ge 4 ]] || die "usage: $0 build|flash|capture|collect|run v1|v2 <build type> AC6|GCC"
CMD="$1"; LIB="$2"; BT="$3"; TC="$4"
case "$LIB" in v1) LIBDIR="$LIB_V1" ;; v2) LIBDIR="$LIB_V2" ;; *) die "lib must be v1 or v2" ;; esac
case "$BT" in RTX5|FreeRTOS|RTX5-NoHeap|FreeRTOS-NoHeap|RTX5-HwCheck|RTX5-Soak) ;; *) die "unknown build type $BT" ;; esac
case "$TC" in AC6|GCC) ;; *) die "toolchain must be AC6 or GCC" ;; esac

OUTDIR="$HERE/out/DevKit-E8/$BT/$TC"
CONTEXT="M55_HP.$BT+DevKit-E8"

lib_commit()  { git -C "$LIBDIR" rev-parse HEAD; }
lib_dirty()   { [[ -n "$(git -C "$LIBDIR" status --porcelain --untracked-files=no)" ]] && echo 1 || echo 0; }

do_build() {
    [[ -f "$LIBDIR/OliverFaust.CSP4CMSIS.pdsc" ]] || die "no OliverFaust.CSP4CMSIS.pdsc in $LIBDIR"
    ln -sfn "$LIBDIR" "$HERE/M55_HP/csp4cmsis_under_test"
    cat > "$HERE/M55_HP/lib_version.h" <<EOF
/* Generated by hwtest.sh -- do not edit, not tracked. */
#define HWTEST_LIB_NAME     "$LIB ($(git -C "$LIBDIR" describe --always --tags 2>/dev/null || echo '?'))"
#define HWTEST_LIB_COMMIT   "$(lib_commit)"
#define HWTEST_LIB_DIRTY    $(lib_dirty)
#define HWTEST_BUILD_TYPE   "$BT"
#define HWTEST_TOOLCHAIN_ID "$TC"
EOF
    # shellcheck disable=SC2086
    cbuild "$HERE/CSP4CMSIS_HwTest.csolution.yml" -c "$CONTEXT" --toolchain "$TC" --packs --rebuild ${HWTEST_EXTRA:-}
    # Which library sources were compiled (must be the tree under test).
    local srcs
    srcs=$(grep -o '"file": *"[^"]*/csp4cmsis/src/[a-z_]*\.cpp"' "$HERE"/tmp/*/compile_commands.json 2>/dev/null \
           | sed 's/.*"\([^"]*\)"$/\1/' | sort -u || true)
    echo "library sources compiled:"; echo "$srcs" | sed 's/^/  /'
    [[ -f "$OUTDIR/M55_HP.bin" ]] || die "no image at $OUTDIR/M55_HP.bin"
    echo "image: $OUTDIR/M55_HP.bin (library $LIB @ $(lib_commit), dirty=$(lib_dirty))"
}

do_flash() {
    [[ -x "$SETOOLS/app-write-mram" ]] || die "SETOOLS not found at $SETOOLS (set HWTEST_SETOOLS)"
    [[ -f "$OUTDIR/M55_HP.bin" ]] || die "build first: no $OUTDIR/M55_HP.bin"
    mkdir -p "$SETOOLS/build/images" "$SETOOLS/build/config"
    cp "$OUTDIR/M55_HP.bin" "$SETOOLS/build/images/$IMAGE_NAME"
    cp "$HERE/app-cfg-hwtest.json" "$SETOOLS/build/config/app-cfg-hwtest.json"
    ( cd "$SETOOLS" \
      && ./app-gen-toc -f build/config/app-cfg-hwtest.json -o build/AppTocPackage.bin \
      && ./app-write-mram -a )
}

do_capture() {
    mkdir -p "$HERE/results"
    local log="$HERE/results/$(date +%Y-%m-%d_%H%M)_${LIB}_${BT}_${TC}.txt"
    local tcver
    if [[ "$TC" == AC6 ]]; then tcver=$("${AC6_TOOLCHAIN_6_24_0:-}/armclang" --version 2>/dev/null | sed -n 2p || true)
    else tcver=$("${GCC_TOOLCHAIN_14_2_1:-}/arm-none-eabi-gcc" --version 2>/dev/null | head -1 || true); fi
    echo "capturing $UART -> $log (timeout ${TIMEOUT}s). Reset the board now if it does not start by itself."
    python3 "$HERE/capture.py" "$UART" "$log" "$TIMEOUT" \
        "config: lib=$LIB build type=$BT toolchain=$TC" \
        "library: $LIBDIR @ $(lib_commit) dirty=$(lib_dirty)" \
        "harness: Alif-DK-E8-CSP4CMSIS @ $(git -C "$REPO" rev-parse HEAD) dirty=$([[ -n "$(git -C "$REPO" status --porcelain --untracked-files=no)" ]] && echo 1 || echo 0)" \
        "toolchain: $tcver; cbuild $(cbuild --version | head -1)" \
        "image: $OUTDIR/M55_HP.bin sha256=$(sha256sum "$OUTDIR/M55_HP.bin" | cut -c1-16)" \
        "captured: $(date -Iseconds) from $UART"
}

# Alternative to capture: take the last complete run from a console log written
# by another program (e.g. minicom -C <file>); only one program may have the
# port open. The board's own header must name the library commit under test.
do_collect() {
    local src="${HWTEST_CONSOLE_LOG:-$HOME/hwtest_console.log}"
    [[ -r "$src" ]] || die "no console log at $src (set HWTEST_CONSOLE_LOG)"
    mkdir -p "$HERE/results"
    local log="$HERE/results/$(date +%Y-%m-%d_%H%M)_${LIB}_${BT}_${TC}.txt"
    local run
    run=$(tr -d '\r\004' < "$src" | awk '/=== HWTEST header ===/{buf=""; on=1} on{buf=buf $0 "\n"} END{printf "%s", buf}')
    [[ -n "$run" ]] || die "no HWTEST header in $src"
    grep -q "^SUMMARY:" <<<"$run" || die "the last run in $src has no SUMMARY line (not finished?)"
    grep -q "commit $(lib_commit)" <<<"$run" || die "the last run in $src is not library $LIB @ $(lib_commit)"
    grep -q "build type: $BT; toolchain: $TC " <<<"$run" || die "the last run in $src is not build type $BT with $TC"
    {
        echo "# config: lib=$LIB build type=$BT toolchain=$TC"
        echo "# library: $LIBDIR @ $(lib_commit) dirty=$(lib_dirty)"
        echo "# harness: Alif-DK-E8-CSP4CMSIS @ $(git -C "$REPO" rev-parse HEAD)"
        echo "# image: $OUTDIR/M55_HP.bin sha256=$(sha256sum "$OUTDIR/M55_HP.bin" | cut -c1-16)"
        echo "# console: last run in $src (minicom log), collected $(date -Iseconds)"
        printf '%s' "$run"
    } > "$log"
    echo "$log"; grep -E "^(RESULT|SUMMARY)" "$log" | tail -3
}

case "$CMD" in
    build)   do_build ;;
    flash)   do_flash ;;
    capture) do_capture ;;
    collect) do_collect ;;
    run)     do_build; do_flash
             [[ "${HWTEST_SW4_PROMPT:-1}" == 1 ]] && read -r -p "Set SW4 to UART (console), then press Enter: " _
             do_capture ;;
    *)       die "unknown command $CMD" ;;
esac
