/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.0
 *
 * Project: 'M55_HP.Debug+DevKit-E8' 
 * Target:  'Debug+DevKit-E8' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.3.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.26.5 */
#define RTE_ETHOS_U_CORE_DRIVER
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.3.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.3.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.3.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.3.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.3.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* AlifSemiconductor::BSP:External peripherals:ICM42670P Accelerometer@2.2.0 */
#define RTE_Drivers_ICM42670P           /* Driver ICM42670P */
/* AlifSemiconductor::CMSIS Driver:USART@2.2.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.2.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:I3C@2.2.0 */
#define RTE_Drivers_I3C                    /* Driver I3C */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.2.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* PyTorch::Machine Learning:ExecuTorch:Backend EthosU@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_BACKEND_ETHOS_U     /* ExecuTorch Ethos-U Backend */
/* PyTorch::Machine Learning:ExecuTorch:Kernel Registration@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_KERNEL_REGISTRATION     /* ExecuTorch Kernel Registration */
/* PyTorch::Machine Learning:ExecuTorch:Kernel Utils@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_KERNEL_UTILS     /* ExecuTorch Kernel Utils */
/* PyTorch::Machine Learning:ExecuTorch:Operators Quantized dequantize@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_OP_QUANTIZED_DEQUANTIZE     /* ExecuTorch op_dequantize */
/* PyTorch::Machine Learning:ExecuTorch:Operators Quantized quantize@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_OP_QUANTIZED_QUANTIZE     /* ExecuTorch op_quantize */
/* PyTorch::Machine Learning:ExecuTorch:Platform Bare-Metal@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_PLATFORM_BARE_METAL     /* ExecuTorch Bare-Metal PAL */
/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_RUNTIME     /* ExecuTorch Runtime */
/* PyTorch::Machine Learning:ExecuTorch:Stubs RandomOps@1.1.0-rc1-build.12 */
#define RTE_ML_EXECUTORCH_STUBS_RANDOM_OPS     /* ExecuTorch Random Op Stubs */


#endif /* RTE_COMPONENTS_H */
